compile:
	gcc -Wall -Werror -Wextra main.c list.c string_utils.c string_utils2.c dict.c scanner.c

g:
	gcc -Wall -Werror -Wextra main.c list.c string_utils.c string_utils2.c dict.c scanner.c -g

fclean:
	rm *.out
